Fix a bug to save processed IODA IMS files into designated directory
NOAA-PSL/land-DA_update pull request #18
Opened 2023-08-09 19:33 UTC by yuanxue2870

Please review: @ClaraDraper-NOAA. This is the bug fix that we discussed on 08/08. Per your request, I am creating the pull request here. Thank you!

## Describe your changes  
Summarise all code changes included in PR: 
- I comment out lines of code for IODA IMS with "old naming nomenclature" (i.e., ioda.IMSscf.${YYYY}${MM}${DD}.C${RES}.nc)
- I added lines for "new" IODA IMS filenames (i.e., ioda.IMSscf.${YYYY}${MM}${DD}.oro_C${RES}.mx100.nc) to save them properly into the designated directory in case users want to check these files in the output directory without keeping the jedi working directory. 

List any associated PRs  in the submodules.
N/A

## Issue ticket number and link
N/A

## Test output 
Is this PR expected to pass the DA_IMS_test (ie., does it change the output)? 
- Yes, it is expected.

Does it pass the DA_IMS_test? 
- Yes, it does.

If changes to the test results are expected, what are these changes? Provide a link to the output directory when running the test: 
N/A.

## Checklist before requesting a review
- [ ] My branch being merged is up to date with the latest develop. 
Note: It seems that I am behind the latest develop when I cloned this repo. My PR is only associated with changes from Lines 448-456. Nothing else.
- [x] I have performed a self-review of my code by examining the differences that will be merged.
Note: Yes. But again, my branch seems to be behind. There are differences at Lines 241, 346-347, that should **not** be merged.
- [x] I have not made any unnecessary code changes / changed any default behavior.
- [x] My code passes the DA_IMS_test, or differences can be explained.

2023-08-18 21:47 UTC, ClaraDraper-NOAA requested changes
Yuan, thanks for submitting this. Please see comments below.

2023-08-18 21:47 UTC, ClaraDraper-NOAA commented on do_landDA.sh
> -         export do_DA="YES"
I don't remember why I exported this, but I think you're right that it's no longer needed. Good catch.

2023-08-18 21:47 UTC, ClaraDraper-NOAA commented on do_landDA.sh
> -    ln -s ${TPATH}/${TSTUB}* ${JEDIWORKDIR}
I think we need this. In letkfoi_snow.yaml this block of code: 

  time invariant fields:
    state fields:
      datetime: XXYYYP-XXMP-XXDPTXXHP:00:00Z
      filetype: fms restart
      skip coupler file: true
      state variables: [orog_filt,slmsk]
      datapath: ./
      filename_orog: XXTSTUB.nc
      filename_sfcd: XXYYYYXXMMXXDD.XXHH0000.sfc_data.nc
    derived fields: [nominal_surface_pressure]

reads in the orography file from XXTSTUB.nc, which is what is being linked into the work directory here. 

are you sure that it passed the test without it? Please make sure that you code is the same as what you pushed, and that you are running the test using a new workdir.

2023-08-18 21:47 UTC, ClaraDraper-NOAA commented on do_landDA.sh
> +  # if [[ -e ${JEDIWORKDIR}/ioda.IMSscf.${YYYY}${MM}${DD}.C${RES}.nc ]]; then
Please delete the commented-out lines.

2023-08-18 21:47 UTC, ClaraDraper-NOAA commented on do_landDA.sh
> +  if [[ -e ${JEDIWORKDIR}/ioda.IMSscf.${YYYY}${MM}${DD}.oro_C${RES}.mx100.nc ]]; then
I'd like to avoid hard-coding the mx100 (this is the resolution of the ocean model). You can replace your "oro_C${RES}.mx100" with "$TSTUB.  $TSTUB is the start of the orography file name, and this is what is appended to the IMS file name by calcfIMS.

2023-08-28 14:15 UTC, yuanxue2870 commented on do_landDA.sh
> -    ln -s ${TPATH}/${TSTUB}* ${JEDIWORKDIR}
This is not my edits as I noted in the Checklist since I was behind the latest develop at that time. I now re-uploaded the version that is consistent with the latest develop. Thanks for your time and patience as I am still learning all GitHub related code management.

2023-08-28 14:15 UTC, yuanxue2870 commented on do_landDA.sh
> +  # if [[ -e ${JEDIWORKDIR}/ioda.IMSscf.${YYYY}${MM}${DD}.C${RES}.nc ]]; then
Yes, Done.

2023-08-28 14:16 UTC, yuanxue2870 commented on do_landDA.sh
> +  if [[ -e ${JEDIWORKDIR}/ioda.IMSscf.${YYYY}${MM}${DD}.oro_C${RES}.mx100.nc ]]; then
Agreed. Done.

2023-08-29 20:09 UTC, ClaraDraper-NOAA commented on do_landDA.sh
> -    ln -s ${TPATH}/${TSTUB}* ${JEDIWORKDIR}
@yuanxue2870 This is an annoying feature of dealing with sub-modules. The parent module does not necessarily have the head of the sub-modules checked out, so when you submit a PR you need to manually check that you have the head of any sub-modules that you're PR-ing into. (when you prepare the PR there's an option to see your changes - I always check that quite carefully, as it'll show any issue like this will be obvious).

When you're ready for me to have another look, can you please check "request re-review"?

2023-09-19 22:30 UTC, merged

2023-09-19 22:31 UTC, ClaraDraper-NOAA commented
Thanks Yuan!