Enable GTS DA cycles every 6 hours
NOAA-PSL/land-DA_update pull request #25
Opened 2024-11-15 18:14 UTC by yuanxue2870

## Describe your changes  
Summarise all code changes included in PR: 
1.  Fix bugs for $WINLEN
2.  Correct typos in the do_landDA.sh
3.  Add current Jiarui's GTS yaml and add the elevation check (to be consistent with GHCN.yaml filters)
4.  Enable 6-hr cycle for GTS DA

List any associated PRs in the submodules.
N/A

## Issue ticket number and link
List the git Issue that this PR addresses: 

## Test output 
Is this PR expected to pass the DA_IMS_test (ie., does it change the output)? 
Yes.
Does it pass the DA_IMS_test? 
Yes.
If changes to the test results are expected, what are these changes? Provide a link to the output directory when running the test: 
N/A
## Checklist before requesting a review
- [x] My branch being merged is up to date with the latest develop. 
- [x] I have performed a self-review of my code by examining the differences that will be merged.
- [x] I have not made any unnecessary code changes / changed any default behavior.
- [x] My code passes the DA_IMS_test, or differences can be explained.

2024-11-18 15:34 UTC, yuanxue2870 commented
Please review: @ClaraDraper-NOAA @jiaruidong2017, Thank you!

2024-11-25 02:34 UTC, jiaruidong2017 commented on do_landDA.sh
> +HB=$(printf %02d $(( $HP+$WINLEN/2)))
It is good for the GTS DA. However, it seems there is an issue for the GHCN with $WINLEN=24. For example, GHCN is assimilated at 12z (`$HP=12`), then `$HB=24` of the previous day (`YYYP-MP-DP 24z`), but it should be the 00z of the current day (`YYYY-MM-DD 00z`).

2024-11-25 02:34 UTC, jiaruidong2017 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          minvalue: -999.0
The missing value for `MetaData/stationElevation` is changed to a very large number. Please replace `minvalue: -999.0` with `maxvalue: 999999999.9`.

2024-11-25 02:34 UTC, jiaruidong2017 commented on jedi/fv3-jedi/yaml_files/2DVar/snow.yaml
> +    begin: XXYYYP-XXMP-XXDPTXXHB:00:00Z
For the GHCN DA, this generates `YYYP-MP-DP 24z` here, but we would like to have `YYYY-MM-DD 00z` instead. Therefore, I would suggest to use another set of date/time tags (e.g., `XXYYYB`, `XXMB`, `XXDB` and `XXHB`) for the DA window begin.

2024-11-25 19:23 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          minvalue: -999.0
Current stationElevation maxvalue is 9999. Per conversations with Jiarui on 11/25/2024, Jiarui will double check the value.

2024-11-25 21:04 UTC, yuanxue2870 commented on do_landDA.sh
> +HB=$(printf %02d $(( $HP+$WINLEN/2)))
Revised. Done.

2024-11-25 21:04 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/snow.yaml
> +    begin: XXYYYP-XXMP-XXDPTXXHB:00:00Z
Revised. Done. Thanks for your suggestions!

2024-11-25 22:03 UTC, ClaraDraper-NOAA requested changes
It looks close to me, thanks @yuanxue2870. I'd like to clean up the DA window section a bit though - see specific comments.

2024-11-25 22:03 UTC, ClaraDraper-NOAA commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          minvalue: -999.0
I'm not sure what the unit is, but I'm guessing we can get higher than that. @jiaruidong2017 Is it possible to set the elevation missing value to a different value?

2024-11-25 22:03 UTC, ClaraDraper-NOAA commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          size where true: 5
@jiaruidong2017 out of curiosity, what is "size where true"?

2024-11-25 22:03 UTC, ClaraDraper-NOAA commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +        maxvalue: 2000.0
Is this in mm? In that case, 2m seems a bit low for a max threshold? @jiaruidong2017

2024-11-25 22:03 UTC, ClaraDraper-NOAA commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          name: Halo
I thought the halo distribution was for EnKF only?

2024-11-25 22:03 UTC, ClaraDraper-NOAA commented on jedi/fv3-jedi/yaml_files/2DVar/snow_I.yaml
>      begin: XXYYYP-XXMP-XXDPT12:00:00Z
This time should be changed too (not hard-coded to 12).

2024-11-25 22:03 UTC, ClaraDraper-NOAA commented on do_landDA.sh
> +HB=$(printf %02d $(( $HP+$WINLEN/2)))
The issue here is not GHCN v. GTS, it's 2DVar v LETKF-OI. The Var window is centered on the analysis time, while the LETKF window ends at the analysis time. 

To make this clearer, please update the code here to calculate the window begging time, based on the DAalg 

so if (Var) 
begin = time - 1/2 window 
else if (LETKFOI) 
begin = time - window
end

Then when we fill in the yamls, there should only be one set of XXHHB, etc variables.

(you can leave the *P variable calculation in for now, as we're using it to get the GHCN obs, but I will delete that section of code soon).

2024-11-25 22:59 UTC, jiaruidong2017 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          minvalue: -999.0
@ClaraDraper-NOAA The unit is meter. We can definitely set the missing value to the different numbers, and it depends on the preprocess of the ioda format. For this case, we previously used the python converter, and the missing values for elevation were assigned to negative numbers (-999.0). When we didn't use the python converter later, the missing values were kept as the original large positive numbers.

2024-11-25 23:00 UTC, jiaruidong2017 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          size where true: 5
As I remember, it is the dimension of the `is_in` list.

2024-11-25 23:00 UTC, jiaruidong2017 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +        maxvalue: 2000.0
@ClaraDraper-NOAA Yes, it is mm here. Can you suggest a number, and is it okay to use 10m?

2024-11-25 23:51 UTC, jiaruidong2017 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          minvalue: -999.0
I just checked the elevation of the missing elevation in the netCDF file. Below is what I got: 

```
      208.000      218.000      480.000      107.000      121.000      160.000      38.0000      85.0000      103.000      74.0000
  3.40282e+38      79.0000      26.0000      171.000      91.0000      115.000      79.0000      98.0000      152.000      233.000
```
The missing values are very large number (`3.40282e+38`) here. @yuanxue2870 the missing values (9999) you got are probably limited to software you used.

2024-11-26 13:49 UTC, ClaraDraper-NOAA commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +        maxvalue: 2000.0
Yes, use 10 m. That's the upper limit in the model.

2024-11-26 13:55 UTC, ClaraDraper-NOAA commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          minvalue: -999.0
@CoryMartin-NOAA says there is a standard missing value for IODA. I'm guessing there's also then a method to check for it. @jiaruidong2017  - can you please look into the JEDI documentation to see if there's a cleaner way to do this (i.e, it would be better if the logic were  if elevation is missing then discard obs).

2024-11-26 13:56 UTC, ClaraDraper-NOAA commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          size where true: 5
thanks.

2024-11-26 15:12 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          minvalue: -999.0
> I just checked the missing elevation in the netCDF file. Below is what I got:
> 
> ```
>       208.000      218.000      480.000      107.000      121.000      160.000      38.0000      85.0000      103.000      74.0000
>   3.40282e+38      79.0000      26.0000      171.000      91.0000      115.000      79.0000      98.0000      152.000      233.000
> ```
> 
> The missing values are very large number (`3.40282e+38`) here. @yuanxue2870 the missing values (9999) you got are probably limited to software you used.

Hi Jiarui, Thanks for checking. The values of 3.40282e+38 have been set to NaNs in ncdump, ncview, and Matlab (the three software that we looked into yesterday). But based on the plot, it seems to me that 9999 is also a filled-in value.

2024-11-26 15:16 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          minvalue: -999.0
![Capture](https://github.com/user-attachments/assets/1765bd35-ff63-43b5-9de1-78ea851e57af)

The maximum elevation value for each file is plotted as a function of the time (every 6 hours). NaNs (i.e., 3.40282e+38) are omitted. The y-axis is capped at 9999.

2024-11-26 16:14 UTC, ClaraDraper-NOAA commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          minvalue: -999.0
@yuanxue2870 and I discussed this. reasonable limits for screening unrealistic snow depth would be -200 to 9900 m. Let;'s use these here, and that will catch missing values for now too.

2024-11-26 18:47 UTC, yuanxue2870 commented on do_landDA.sh
> +HB=$(printf %02d $(( $HP+$WINLEN/2)))
Revised. Done.

2024-11-26 18:48 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          minvalue: -999.0
Done.

2024-11-26 18:49 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/snow_I.yaml
>      begin: XXYYYP-XXMP-XXDPT12:00:00Z
Done.

2024-11-26 19:25 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +        maxvalue: 2000.0
The upper limit of the snow depth is varying as a function of the surface. Among all different surfaces, the maximum upper limit set for snow depth in Noah-MP is 55m. This value is also confirmed by Helin based on email exchanges on 11/26/2024. Clara suggests using 20m per discussions on 11/26/2024.

2024-11-26 19:48 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          name: Halo
@jiaruidong2017 Please advise when you get a chance. Thank you!

2024-11-27 01:23 UTC, jiaruidong2017 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          name: Halo
The halo distribution is required by the letkfoi. You can just removed the distribution section for the 2dvar here.

2024-11-27 16:35 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          name: Halo
Thanks. Done.

2024-12-02 21:00 UTC, jiaruidong2017 commented on jedi/fv3-jedi/yaml_files/2DVar/GTS.yaml
> +          maxvalue: 9900.0
It looks good to me now. I would suggest to use the traditional missing values, such as -999.0 for `minvalue` and 9999.0 for `maxvalue`.

2024-12-03 15:56 UTC, ClaraDraper-NOAA approved these changes
This looks great, thanks @yuanxue2870

2024-12-03 15:57 UTC, merged