Enable MADIS DA
NOAA-PSL/land-DA_update pull request #28
Opened 2024-12-05 20:06 UTC by yuanxue2870

## Describe your changes  
Summarise all code changes included in PR: 
1. add MADIS yaml
2. add the MADIS observation directory

List any associated PRs  in the submodules.

## Issue ticket number and link
List the git Issue that this PR addresses: 

## Test output 
Is this PR expected to pass the DA_IMS_test (ie., does it change the output)? 
Yes.
Does it pass the DA_IMS_test? 
Yes.
If changes to the test results are expected, what are these changes? Provide a link to the output directory when running the test: 
N/A
## Checklist before requesting a review
- [x] My branch being merged is up to date with the latest develop. 
- [x] I have performed a self-review of my code by examining the differences that will be merged.
- [x] I have not made any unnecessary code changes / changed any default behavior.
- [x] My code passes the DA_IMS_test, or differences can be explained.

2024-12-13 19:55 UTC, jiaruidong2017 requested changes
Suggest to make the changes in consistent with the global-workflow for now.

Also make the corresponding changes to the GTS.yaml. It is better to rename the GTS to the specific name (e.g., sfcsno) indicating the different GTS data sources.

2024-12-13 19:55 UTC, jiaruidong2017 commented on jedi/fv3-jedi/yaml_files/2DVar/MADIS.yaml
> +        maxvalue: 2000.0
```suggestion
        maxvalue: 20000.0
```

2024-12-13 19:55 UTC, jiaruidong2017 commented on jedi/fv3-jedi/yaml_files/2DVar/MADIS.yaml
> +          minvalue: -999.0
```suggestion
          value: is_valid
```

2024-12-13 20:07 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/MADIS.yaml
> +        maxvalue: 2000.0
Done. Thanks!

2024-12-13 20:13 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/MADIS.yaml
> +          minvalue: -999.0
Thanks for pointing this out. I think I would still need to confirm with Clara on this point. For GTS yaml, we used [-200, 9900] as the min and max value. Based on your analysis presented on Thursday 12/12/2024, you would prefer using "is_valid". But the preliminary conclusion from our Thursday meeting seems to be we might need three elevation filters in this case: 1) filtered missing values; 2) filtered unreasonable elevation values outside of the [-200, 9900] range; and 3) filtered elevation difference > 200m. I have not looked into the MADIS observations in detail to get the range yet. I will do so next week. Stay tuned. Thanks.

2024-12-13 20:14 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/MADIS.yaml
> +        maxvalue: 2000.0
I will confirm with Clara on whether to change the name from GTS to sfcsno on next Tuesday. Thanks!

2024-12-13 21:04 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/MADIS.yaml
> +          minvalue: -999.0
The min elevation of MADIS stations is typically greater than 0, the max elevation of MADIS stations is often being 4328.2m. However, MADIS does have some unreasonable maximum elevation (other than the missing value set at 9.96e36). I personally think the [-200, 9900] range can also be reused for MADIS. But I will confirm with Clara on Tuesday.

![Capture](https://github.com/user-attachments/assets/721f9449-b251-4fd1-aa07-dd5babcac3aa)

2024-12-17 16:48 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/MADIS.yaml
> +          minvalue: -999.0
Per discussions with Clara on 12/17/2025, will keep doing more tests to make sure that the three filters can all be captured properly in the yaml.

2024-12-17 19:33 UTC, yuanxue2870 commented
> Suggest to make the changes in consistent with the global-workflow for now.
> 
> Also make the corresponding changes to the GTS.yaml. It is better to rename the GTS to the specific name (e.g., sfcsno) indicating the different GTS data sources.

Now, "GTS" has been renamed as "SFCSNO" per your suggestion after confirming with Clara on 12/17/2024. Thank you!

2024-12-19 19:05 UTC, yuanxue2870 commented on jedi/fv3-jedi/yaml_files/2DVar/MADIS.yaml
> +          minvalue: -999.0
Per discussions with the land team on 12/19/2024, no more filter tests are needed. Am adding all three filters.

2024-12-20 17:07 UTC, yuanxue2870 commented
All done. Please re-review: @jiaruidong2017 @ClaraDraper-NOAA Thank you!

2024-12-20 17:16 UTC, ClaraDraper-NOAA commented
Thanks @yuanxue2870 . i'm in the middle of merging a largish PR from Tseganeh -  so you may need to deal with some merge conflicts on this one.

2024-12-20 17:21 UTC, yuanxue2870 commented
> Thanks @yuanxue2870 . i'm in the middle of merging a largish PR from Tseganeh - so you may need to deal with some merge conflicts on this one.

OK. I will wait for the /develop updates then.

2024-12-20 17:53 UTC, jiaruidong2017 approved these changes
Looks good to me. Thanks.

2024-12-20 20:34 UTC, yuanxue2870 commented
> Looks good to me. Thanks.

Thanks!

2024-12-20 20:34 UTC, yuanxue2870 commented
> > Thanks @yuanxue2870 . i'm in the middle of merging a largish PR from Tseganeh - so you may need to deal with some merge conflicts on this one.
> 
> OK. I will wait for the /develop updates then.

Looks like there are no conflicts for this one.

2025-04-07 22:11 UTC, merged